In [2]:
import numpy as np

In [5]:
fitness_data = np.array([[5000, 200, 6],[7000, 250, 7],[6500, 230, 6],[8000, 300, 8],[9000, 
320, 7],[7500, 270, 6],[12000, 400, 5]])  

================== Explore the array ===============

In [6]:
# Number of dimensions 
np.ndim(fitness_data)

2

In [7]:
#Shape of the array  
np.shape(fitness_data)

(7, 3)

In [8]:
 # Total number of elements  
np.size(fitness_data)

21

======================= Slice the data============

In [9]:
# All step values 
steps = fitness_data[ : , 0]
print(steps)

[ 5000  7000  6500  8000  9000  7500 12000]


In [10]:
# All calorie values 
calorie = fitness_data[: , 1]
print(calorie)

[200 250 230 300 320 270 400]


In [11]:
# All sleep values
sleep_hours = fitness_data[:, 2]
print(sleep_hours)

[6 7 6 8 7 6 5]


In [12]:
# First 3 days 
First_3_days = fitness_data[0:3 , :] 
print(First_3_days)

[[5000  200    6]
 [7000  250    7]
 [6500  230    6]]


In [13]:
# Steps and calories only 
col0_col1 = fitness_data[: , 0:2]
print(col0_col1)

[[ 5000   200]
 [ 7000   250]
 [ 6500   230]
 [ 8000   300]
 [ 9000   320]
 [ 7500   270]
 [12000   400]]


======================= Reshape the data =============

In [14]:
# Reshape the steps array into a column (7,1) 
np.reshape( steps,(7,1))


array([[ 5000],
       [ 7000],
       [ 6500],
       [ 8000],
       [ 9000],
       [ 7500],
       [12000]])

In [15]:
# Reshape the full dataset into shape (3,7) 
np.reshape(fitness_data,(3,7))

array([[ 5000,   200,     6,  7000,   250,     7,  6500],
       [  230,     6,  8000,   300,     8,  9000,   320],
       [    7,  7500,   270,     6, 12000,   400,     5]])

In [16]:
print(steps>8000)

[False False False False  True False  True]


======================= Filter the data =================

In [17]:
fitness_data[steps>8000]

array([[ 9000,   320,     7],
       [12000,   400,     5]])

In [26]:
fitness_data[sleep_hours < 6]

array([[12000,   400,     5]])

In [27]:
fitness_data[calorie>300]

array([[ 9000,   320,     7],
       [12000,   400,     5]])

======================== Use statistical functions ============

In [42]:
np.mean( steps )

np.float64(7857.142857142857)

In [45]:
np.max(steps)

np.int64(12000)

In [46]:
np.min(sleep_hours)

np.int64(5)

In [47]:
np.std(calorie)

np.float64(61.278887398649196)

In [48]:
range_of_steps = np.max(steps) - np.min(steps)
print(range_of_steps)

7000


========================= Turn results into insight ===========

In [ ]:
# I noticed that the array is 2d and size 21 items .
All_days = fitness_data[: , :] 
print(All_days)


[[ 5000   200     6]
 [ 7000   250     7]
 [ 6500   230     6]
 [ 8000   300     8]
 [ 9000   320     7]
 [ 7500   270     6]
 [12000   400     5]]
